create or replace package pkg_manage_user_ipacs is

  procedure p_insert_user(p_user_desc                 in NVARCHAR2,
                          p_user_password             in NVARCHAR2,
                          p_enabled                   in NUMBER,
                          p_add_by                    in NVARCHAR2,
                          p_add_date                  in DATE,
                          p_mod_by                    in NVARCHAR2,
                          p_mod_date                  in DATE,
                          p_last_passwrod_change_date in DATE,
                          p_default_password          in NVARCHAR2,
                          p_last_login_date           in DATE,
                          p_block_user_count          in NUMBER,
                          p_user_last_name            in VARCHAR2,
                          p_otp_flag                  in VARCHAR2,
                          p_firebase_token            in VARCHAR2,
                          p_user_name                 in VARCHAR2,
                          p_user_type_id              in NUMBER,
                          p_user_zone_id              in NUMBER,
                          p_user_hub_id               in NUMBER,
                          p_user_area_id              in NUMBER,
                          p_user_contact_no           in NVARCHAR2,
                          p_user_email_id             in NVARCHAR2,
                          p_user_address1             in VARCHAR2,
                          p_user_address2             in VARCHAR2,
                          p_user_address3             in VARCHAR2,
                          p_user_postal_code          in NVARCHAR2,
                          p_user_parent_id            in NVARCHAR2,
                          p_user_status               in NUMBER,
                          p_user_longitude            in NVARCHAR2,
                          p_user_latitude             in NVARCHAR2,
                          p_comments                  in NCLOB,
                          p_suspend_id                in NUMBER,
                          p_user_secondary_contact    in NVARCHAR2,
                          p_staff                     in NUMBER,
                          p_user_agency               in NVARCHAR2,
                          p_postal_code               in NVARCHAR2,
                          p_pin_no                    in NVARCHAR2,
                          p_vat_no                    in NVARCHAR2,
                          p_national_id               in NVARCHAR2,
                          p_start_date                in DATE,
                          p_end_date                  in DATE,
                          p_dept                      in NVARCHAR2,
                          p_activator_name            in VARCHAR2,
                          p_post                      in VARCHAR2,
                          p_owner_name                in VARCHAR2,
                          p_activation_code           in VARCHAR2,
                          p_user_category             in INTEGER,
                          p_dob                       in DATE,
                          p_user_loc_id               in FLOAT,
                          p_suspend_remarks           in VARCHAR2,
                          p_danger_zone               in VARCHAR2,
                          p_first_name                in VARCHAR2,
                          p_last_name                 in VARCHAR2,
                          p_observations              in VARCHAR2,
                          p_rubro                     in VARCHAR2);

  procedure p_relation_user_role(p_user_id  in NVARCHAR2,
                                 p_role     in VARCHAR2,
                                 p_priority in INTEGER);

  procedure p_maxive_insert_user_rol_vertical;

  procedure p_maxive_insert_user_rol_horizontal;

end pkg_manage_user_ipacs;
